services:

  apache:
    container_name: ${COMPOSE_PROJECT_NAME}_apache
    build:
      context: ./apache
    ports:
      - "80:80"
    volumes:
      - ./../public:/usr/local/apache2/htdocs
      - ./../logs/apache:/usr/local/apache2/logs

  php:
    build:
      context: ./php
    container_name: ${COMPOSE_PROJECT_NAME}_php
    volumes:
      - ./../public:/var/www/html
    depends_on:
      - apache